DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"February"}, 'dim_date'[Month Name])

	VAR __ValueFilterDM1 = 
		FILTER(
			KEEPFILTERS(
				SUMMARIZECOLUMNS(
					'dim_product'[product_name],
					__DS0FilterTable,
					"Total_YTD_Last_Year", [Total YTD Last Year],
					"Target_YTD_Last_Year", [Target YTD Last Year],
					"Last_Year_Varriance", [Last Year Varriance],
					"v__Varriance_Last_Year", [% Varriance Last Year],
					"Achievment_Measure_Last_year", [Achievment Measure Last year]
				)
			),
			[Achievment_Measure_Last_year] <> "Achieved"
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL('dim_product'[product_name], "IsGrandTotalRowTotal"),
			__DS0FilterTable,
			__ValueFilterDM1,
			"Total_YTD_Last_Year", [Total YTD Last Year],
			"Target_YTD_Last_Year", [Target YTD Last Year],
			"Last_Year_Varriance", [Last Year Varriance],
			"v__Varriance_Last_Year", [% Varriance Last Year],
			"Achievment_Measure_Last_year", [Achievment Measure Last year]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(502, __DS0Core, [IsGrandTotalRowTotal], 0, 'dim_product'[product_name], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC, 'dim_product'[product_name]