DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"February"}, 'dim_date'[Month Name])

	VAR __ValueFilterDM1 = 
		FILTER(
			KEEPFILTERS(
				SUMMARIZECOLUMNS(
					'dim_product'[product_name],
					__DS0FilterTable,
					"Total_YTD", [Total YTD],
					"Target_YTD", [Target YTD],
					"Achievment_Status", [Achievment Status],
					"Varriance", [Varriance],
					"v__Varriance", [% Varriance]
				)
			),
			[Achievment_Status] <> "Achieved"
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL('dim_product'[product_name], "IsGrandTotalRowTotal"),
			__DS0FilterTable,
			__ValueFilterDM1,
			"Total_YTD", [Total YTD],
			"Target_YTD", [Target YTD],
			"Achievment_Status", [Achievment Status],
			"Varriance", [Varriance],
			"v__Varriance", [% Varriance]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(502, __DS0Core, [IsGrandTotalRowTotal], 0, 'dim_product'[product_name], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC, 'dim_product'[product_name]